# Copyright (c) 2017-present, Facebook, Inc.
# All rights reserved.
#
# This source code is licensed under the BSD-style license found in the
# LICENSE file in the root directory of this source tree.
import functools
import inspect
import types
from abc import ABC, abstractmethod
from collections import defaultdict
from itertools import chain
from typing import (
    Any,
    Callable,
    DefaultDict,
    Dict,
    Generator,
    Generic,
    Iterable,
    Iterator,
    List,
    Set,
    Tuple,
    Type,
    TypeVar,
    Union,
)

from mypy_extensions import TypedDict

from monkeytype.compat import (
    is_any,
    is_generic,
    is_generic_of,
    is_typed_dict,
    is_union,
    name_of_generic,
    types_equal,
)

DUMMY_TYPED_DICT_NAME = "DUMMY_NAME"
DUMMY_REQUIRED_TYPED_DICT_NAME = "REQUIRED_TYPED_DICT_NAME"
DUMMY_OPTIONAL_TYPED_DICT_NAME = "OPTIONAL_TYPED_DICT_NAME"


# Functions like shrink_types and get_type construct new types at runtime.
# Mypy cannot currently type these functions, so the type signatures for this
# file live in typing.pyi.


def is_list(typ: type) -> bool:
    pass


def make_typed_dict(*, required_fields=None, optional_fields=None) -> type:
    pass


def field_annotations(typed_dict) -> Tuple[Dict[str, type], Dict[str, type]]:
    """Return the required and optional fields in the TypedDict."""
    pass


def is_anonymous_typed_dict(typ: type) -> bool:
    """Return true if this is an anonymous TypedDict as generated by MonkeyType."""
    pass


def shrink_typed_dict_types(typed_dicts: List[type], max_typed_dict_size: int) -> type:
    """Shrink a list of TypedDicts into one with the required fields and the optional fields.
    Required fields are keys that appear as a required field in all the TypedDicts.
    Optional fields are those that appear as a required field in only some
    of the TypedDicts or appear as a optional field in even one TypedDict.
    If the same key has multiple value types, then its value is the Union of the value types.
    """
    pass


def shrink_types(types, max_typed_dict_size):
    """Return the smallest type equivalent to Union[types].
    If all the types are anonymous TypedDicts, shrink them ourselves.
    Otherwise, recursively turn the anonymous TypedDicts into Dicts.
    Union will handle deduplicating types (both by equality and subtype relationships).
    """
    pass


def make_iterator(typ):
    pass


def make_generator(yield_typ, send_typ, return_typ):
    pass


_BUILTIN_CALLABLE_TYPES = (
    types.FunctionType,
    types.LambdaType,
    types.MethodType,
    types.BuiltinMethodType,
    types.BuiltinFunctionType,
)


def get_dict_type(dct, max_typed_dict_size):
    """Return a TypedDict for `dct` if all the keys are strings.
    Else, default to the union of the keys and of the values."""
    pass


def get_type(obj, max_typed_dict_size):
    """Return the static type that would be used in a type hint"""
    pass


NoneType = type(None)
NotImplementedType = type(NotImplemented)
mappingproxy = type(range.__dict__)


T = TypeVar("T")


class GenericTypeRewriter(Generic[T], ABC):
    @abstractmethod
    def make_builtin_tuple(self, elements): pass

    @abstractmethod
    def make_container_type(self, container_type, element): pass

    @abstractmethod
    def make_anonymous_typed_dict(self, required_fields, optional_fields): pass

    @abstractmethod
    def make_builtin_typed_dict(self, name, annotations, total): pass

    @abstractmethod
    def generic_rewrite(self, typ): pass

    @abstractmethod
    def rewrite_container_type(self, container_type): pass

    @abstractmethod
    def rewrite_malformed_container(self, container): pass

    @abstractmethod
    def rewrite_type_variable(self, type_variable): pass

    def _rewrite_container(self, cls, container):
        pass

    def rewrite_Dict(self, dct):
        pass

    def rewrite_List(self, lst):
        pass

    def rewrite_Set(self, st):
        pass

    def rewrite_Tuple(self, tup):
        pass

    def rewrite_Generator(self, generator):
        pass

    def rewrite_anonymous_TypedDict(self, typed_dict):
        pass

    def rewrite_TypedDict(self, typed_dict):
        pass

    def rewrite_Union(self, union):
        pass

    def rewrite(self, typ):
        pass


class TypeRewriter(GenericTypeRewriter[type]):
    """TypeRewriter provides a visitor for rewriting parts of types"""

    def make_anonymous_typed_dict(self, required_fields, optional_fields):
        pass

    def make_builtin_typed_dict(self, name, annotations, total):
        pass

    def generic_rewrite(self, typ):
        pass

    def rewrite_container_type(self, container_type):
        pass

    def rewrite_malformed_container(self, container):
        pass

    def rewrite_type_variable(self, type_variable):
        pass

    def make_builtin_tuple(self, elements):
        pass

    def make_container_type(self, container_type, element):
        pass


class RemoveEmptyContainers(TypeRewriter):
    """Remove redundant, empty containers from union types.

    Empty containers are typed as C[Any] by MonkeyType. They should be removed
    if there is a single concrete, non-null type in the Union. For example,

        Union[Set[Any], Set[int]] -> Set[int]

    Union[] handles the case where there is only a single type left after
    removing the empty container.
    """

    def _is_empty(self, typ):
        pass

    def rewrite_Union(self, union):
        pass


class RewriteConfigDict(TypeRewriter):
    """Union[Dict[K, V1], ..., Dict[K, VN]] -> Dict[K, Union[V1, ..., VN]]"""

    def rewrite_Union(self, union):
        pass


class RewriteLargeUnion(TypeRewriter):
    """Rewrite Union[T1, ..., TN] as Any for large N."""

    def __init__(self, max_union_len: int = 5):
        super().__init__()
        self.max_union_len = max_union_len

    def _rewrite_to_tuple(self, union):
        """Union[Tuple[V, ..., V], Tuple[V, ..., V], ...] -> Tuple[V, ...]"""
        pass

    def rewrite_Union(self, union):
        pass


class RewriteAnonymousTypedDictToDict(TypeRewriter):
    """TypedDict('Foo', {"k": v1, ...}) -> Dict[str, Union[v1, ...]]."""

    def rewrite_anonymous_TypedDict(self, typed_dict):
        pass


class ChainedRewriter(TypeRewriter):
    def __init__(self, rewriters: Iterable[TypeRewriter]) -> None:
        self.rewriters = rewriters

    def rewrite(self, typ):
        pass


class NoOpRewriter(TypeRewriter):
    def rewrite(self, typ):
        pass


class RewriteGenerator(TypeRewriter):
    """Returns an Iterator, if the send_type and return_type of a Generator is None"""

    def rewrite_Generator(self, typ):
        pass


class RewriteMostSpecificCommonBase(TypeRewriter):
    """
    Relace a union of classes by the most specific
    common base of its members (while avoiding multiple
    inheritance), i.e.,

    Union[Derived1, Derived2] -> Base
    """

    def _compute_bases(self, klass):
        """
        Return list of bases of a given class,
        going from general (i.e., closer to object)
        to specific (i.e., closer to class).
        The list ends with the class itself, its
        first element is the most general base of
        the class up to (but excluding) any
        base class having multiple inheritance
        or the object class itself.
        """
        pass

    def _merge_common_bases(self, first_bases, second_bases):
        """
        Return list of bases common to both* classes,
        going from general (i.e., closer to object)
        to specific (i.e., closer to both classes).
        """
        pass

    def rewrite_Union(self, union):
        """
        Rewrite the union if possible, if no meaningful rewrite is possible,
        return the original union.
        """
        pass


DEFAULT_REWRITER = ChainedRewriter(
    (
        RemoveEmptyContainers(),
        RewriteConfigDict(),
        RewriteLargeUnion(),
        RewriteGenerator(),
    )
)
